Repository pleo-io/file-distributor, pull requests merged in 2022-11, with the labels that each got.

#71 Send comment on PR errors per line
  src/app.ts
  src/configuration.ts
  src/git.ts
  src/schema-validator.ts
  src/types.ts
  test/configuration.test.ts
  test/git.test.ts
  test/schema-validator.test.ts
  yarn.lock
Labels: minor

#72 Add version as required in the schema
  src/template-schema.json
Labels: minor

#69 Avoid creating PRs with no changes
  src/app.ts
  src/git.ts
  test/app.test.ts
  test/git.test.ts
Labels: patch

#74 Push event ignored in case of branch removal action
  src/app.ts
Labels: patch

#75 Removes support for DataDog APM
  package.json
  src/app.ts
  yarn.lock
Labels: internal

#76 Simplify code and fix createTreeChanges
  src/app.ts
  src/git.ts
  src/templates.ts
  src/types.ts
  test/app.test.ts
Labels: patch

#77 Move comments to checks
  src/app.ts
  src/checks.ts
  src/git.ts
  src/schema-validator.ts
  src/types.ts
  test/checks.test.ts
  test/git.test.ts
Labels: minor

#78 Change start script to inject custom octokit retry options
  package.json
  src/app.ts
  src/start.ts
  test/checks.test.ts
Labels: patch
