Repository pleo-io/file-distributor, pull requests merged in 2022-10, with the labels that each got.

#14 Change expected configuration file naming
  .gitignore
  .vscode/launch.json
  src/app.ts
  src/git.ts
  src/templates.ts
  src/types.ts
Labels: major

#18 Use Docker Hub write token
  .github/workflows/release.yaml
Labels: internal

#20 Add test workflow running on pushes
  .github/workflows/test.yaml
  test/index.test.ts
Labels: internal

#25 Ensure PR descriptions reflects changes made in PRs
  package.json
  src/app.ts
  src/configuration.ts
  src/git.ts
Labels: patch

#26 Prefer console.log to Probot.log to avoid passing the app object around globally
  src/app.ts
  src/configuration.ts
  src/git.ts
  src/templates.ts
Labels: internal

#27 Include IntelliJ .idea run and test configurations
  .idea/runConfigurations/Jest_Tests.xml
  .idea/runConfigurations/Start_App.xml
Labels: internal

#30 Refactor functions to use Octokit directly instead of passing Context parameters
  src/app.ts
  src/configuration.ts
  src/git.ts
  src/templates.ts
  src/types.ts
Labels: internal

#31 Reduce Octokit type across all function parameters
  src/app.ts
  src/configuration.ts
  src/git.ts
  src/templates.ts
Labels: internal

#34 Ensure Jest configuration for testing
  .github/workflows/test.yaml
  .vscode/launch.json
  src/app.ts
  src/configuration.ts
  test/app.test.ts
  test/index.test.ts
Labels: internal

#37 Use Pino JSON logging
  .gitattributes
  package.json
  src/app.ts
  src/configuration.ts
  src/git.ts
  src/templates.ts
  test/app.test.ts
  test/templates.test.ts
  yarn.lock
Labels: internal

#40 Use GitHub Action-compatible delimiters for template rendering
  README.md
  src/templates.ts
  test/templates.test.ts
Labels: major

#39 Prepending headers support
  .env.example
  package.json
  src/git.ts
  src/templates.ts
  src/types.ts
  test/templates.test.ts
  yarn.lock
Labels: minor

#41 Extract and provide basic repository information for template values
  .env.example
  app.yml
  package.json
  src/app.ts
  src/configuration.ts
  src/templates.ts
  src/types.ts
  test/configuration.test.ts
Labels: minor

#43 Validate repository configuration changes on PR creation
  .eslintrc.js
  .vscode/launch.json
  package.json
  src/app.ts
  src/checks.ts
  src/git.ts
  src/schema-validator.ts
  src/template-schema.json
  src/types.ts
  test/app.test.ts
  test/checks.test.ts
  test/git.test.ts
  test/schema-validator.test.ts
  yarn.lock
Labels: minor

#47 Automate linting across project
  .eslintrc.js
  .github/workflows/test.yaml
  package.json
  src/app.ts
  src/git.ts
  src/schema-validator.ts
  src/templates.ts
  test/git.test.ts
  test/templates.test.ts
Labels: internal

#45 Validate value changes based on default template values
  README.md
  package.json
  src/app.ts
  src/checks.ts
  src/configuration.ts
  src/git.ts
  src/schema-validator.ts
  src/template-schema.json
  src/templates.ts
  src/types.ts
  test/checks.test.ts
  test/configuration.test.ts
  test/git.test.ts
  test/schema-validator.test.ts
  tsconfig.json
  yarn.lock
Labels: minor

#50 Set the default template location to '.github/templates.yaml'
  .env.example
  README.md
  src/app.ts
  test/app.test.ts
Labels: minor

#51 Fix App manifest permissions
  app.yml
  yarn.lock
Labels: internal

#44 Fix tests and make probot throw error
  src/app.ts
  test/app.test.ts
  test/fixtures/.autorc.json
  test/fixtures/.kodiak.toml
  test/fixtures/defaults.yaml
Labels: minor

#52 Reduce parameters of implementation by exporting built closures
  src/app.ts
  src/checks.ts
  src/configuration.ts
  src/git.ts
  src/schema-validator.ts
  src/templates.ts
  src/types.ts
  test/app.test.ts
  test/checks.test.ts
  test/configuration.test.ts
  test/git.test.ts
  test/schema-validator.test.ts
  test/templates.test.ts
  yarn.lock
Labels: patch

#54 Hotfix release fetch and noisy error logging
  .eslintrc.js
  package.json
  src/app.ts
  src/templates.ts
  yarn.lock
Labels: patch

#46 Change logging to interpolate using pino
  src/app.ts
  src/configuration.ts
  src/git.ts
  src/schema-validator.ts
  src/templates.ts
Labels: internal

#59 Use SWC for building
  .github/workflows/test.yaml
  .swcrc
  package.json
  tsconfig.json
  yarn.lock
Labels: internal

#57 Support file definitions as strings
  .env.example
  README.md
  src/configuration.ts
  src/schema-validator.ts
  src/template-schema.json
  src/templates.ts
  src/types.ts
  test/templates.test.ts
Labels: minor

#58 Validate configured files are present in template releases
  src/app.ts
  src/schema-validator.ts
  src/templates.ts
  test/schema-validator.test.ts
Labels: minor

#60 Prefer SWC only in tests and CI
  .github/workflows/test.yaml
Labels: internal

#64 Only approve PRs that exclusively change repository configuration
  src/app.ts
Labels: patch

#66 Add pull request events to readme local testing
  README.md
Labels: internal

#63 Add administration permissions for automerge
  app.yml
Labels: internal

#65 Unify logging across implementation
  src/app.ts
  src/configuration.ts
  src/schema-validator.ts
  src/templates.ts
Labels: internal

#68 Use SWC for better CI/test/build performance
  .github/workflows/test.yaml
  .vscode/tasks.json
  Dockerfile
  package.json
Labels: internal

#55 Support sending application traces/metrics to DataDog
  .env.example
  package.json
  src/app.ts
  yarn.lock
Labels: internal
