Repository pleo-io/file-distributor, pull requests merged in 2022-12, with the labels that each got.

#84 Broken yaml bug
  .gitignore
  package.json
  src/app.ts
  src/configuration.ts
  test/configuration.test.ts
  yarn.lock
Labels: patch

#85 Prefer commenting on PRs to submitting reviews
  src/app.ts
  src/git.ts
  test/git.test.ts
Labels: patch

#86 Update CODEOWNERS
  .github/CODEOWNERS
Labels: internal

#87 Fix invalid GitHub endpoint for PR review commenting
  src/git.ts
  test/git.test.ts
Labels: patch

#80 Capture Unhandled errors and add rerun check listener
  app.yml
  src/app.ts
  src/checks.ts
  src/configuration.ts
  src/core-validation.ts
  src/git.ts
  src/types.ts
  test/app.test.ts
  test/checks.test.ts
  yarn.lock
Labels: minor
