Repository pleo-io/file-distributor, pull requests merged in 2023-01, with the labels that each got.

#94 Update Overview.md
  .github/workflows/test.yaml
  docs/Overview.md
Labels: internal

#88 Reorder/simplify main application module
  src/app.ts
  src/checks.ts
  src/core-validation.ts
  src/file-creation.ts
  src/payload-extraction.ts
  src/types.ts
  src/validation.ts
Labels: internal

#89 Simplify checks module and types
  src/app.ts
  src/checks.ts
  src/types.ts
  src/validation.ts
  test/checks.test.ts
Labels: internal

#90 Move GitHub calls to unified module
  src/checks.ts
  src/git.ts
  src/validation.ts
  test/checks.test.ts
Labels: internal

#95 Rename 'template' to 'file'/'release' globally
  src/checks.ts
  src/file-creation.ts
  src/files-schema.json
  src/git.ts
  src/release.ts
  src/schema-validator.ts
  src/types.ts
  src/validation.ts
  test/app.test.ts
  test/checks.test.ts
  test/git.test.ts
  test/schema-validator.test.ts
  test/templates.test.ts
Labels: patch

#97 Use check outcome for logging
  src/validation.ts
Labels: internal

#98 Change dependency bump to patch by default
  .github/renovate.json
Labels: internal

#100 Ensure label creation on PR creation
  src/git.ts
Labels: patch

#99 Extend validation errors for missing files in releases
  src/schema-validator.ts
Labels: patch

#102 Log application version on startup
  src/start.ts
Labels: internal

#103 Ensure the application container image is released on the 'pleo-io' container registry
  .github/CODEOWNERS
Labels: patch, automerge

#104 Create templates.yaml
  .github/templates.yaml
Labels: internal

#101 Fix redundant duplicated testing workflow runs
  .github/workflows/test.yaml
Labels: internal, automerge

#105 Ensure latest changes to the default branch are being included in released container images
  .github/workflows/release.yaml
Labels: internal

#108 Only comment on PR validation failures
  src/git.ts
  src/validation.ts
  test/git.test.ts
Labels: patch, automerge

#110 Extend validation error for missing files to reduce confusion
  src/schema-validator.ts
Labels: patch, automerge

#111 Ensure automerge functionality works as expected
  src/file-creation.ts
  src/git.ts
  src/validation.ts
  test/git.test.ts
Labels: minor, automerge

#109 Add auto-closing of stale PRs
  .github/templates.yaml
Labels: internal, automerge

#113 Enable automerge of repository files
  .github/templates.yaml
Labels: internal, automerge
